### ISSUE TITLE
Rectangular images

### ISSUE THREAD

**Issue by Meulen92** [jingyuanli001/RFR-Inpainting#10]
Hi,

First of all, awesome work. Thank you.

Can we train the model on rectangular images? For example, 128x256?

Thanks for your time.

Kind regards,

Jelmer

**Comment by jingyuanli001** [comment]
Hi,

Thank you for your question.
To the best of my knowledge, there seems to have no explicit technical limitation on the shape of the input image, for the model's pixel-to-pixel design. But some modifications of dataset.py file would be necessary to avoid the cropping and reshaping process. You might focus on the resize method and load_mask method in the Dataset class. I'll try to update the code to make it more flexible but it may take some time. :)

Best
Jingyuan

**Comment by Meulen92** [comment]
That is awesome! Thank you for the quick response. I think I will manage using the pointers you gave me.
