### ISSUE TITLE
RuntimeError trying to test the network

### ISSUE THREAD

**Issue by n00mkrad** [jingyuanli001/RFR-Inpainting#13]
Hello, whenver I try to test a pretrained model, I get the following error:

```
File "D:\AI\RFR-Inpainting\modules\partialconv2d.py", line 55, in forward
    self.update_mask = F.conv2d(mask, self.weight_maskUpdater, bias=None, stride=self.stride, padding=self.padding, dilation=self.dilation, groups=1)
RuntimeError: Given groups=1, weight of size [64, 3, 7, 7], expected input[1, 9, 256, 256] to have 3 channels, but got 9 channels instead
```

**Comment by Xiefan-Guo** [comment]
You can modify model.py as follows, it works.

```
            for items in train_loader:
                gt_images, masks = self.__cuda__(*items)
                masks = torch.cat([masks]*3, dim = 1)
                masked_images = gt_images * masks
                self.forward(masked_images, masks, gt_images)
                self.update_parameters()
                self.iter += 1
```

**Comment by styler00dollar** [comment]
This solution did not work for me. The multiplication with 3 creates an error, even if the input is a single channel image. With this it should be possible to input mask (black/white) and image (color) as RGB24. Replace line 84-86 in `model.py` with:
```for items in train_loader:
    gt_images, masks = self.__cuda__(*items)
    masks = torch.cat([masks], dim = 1)
    masked_images = gt_images * masks```

**Comment by GGaoYipeng** [comment]
> Hello, whenver I try to test a pretrained model, I get the following error:
> 
> ```
> File "D:\AI\RFR-Inpainting\modules\partialconv2d.py", line 55, in forward
>     self.update_mask = F.conv2d(mask, self.weight_maskUpdater, bias=None, stride=self.stride, padding=self.padding, dilation=self.dilation, groups=1)
> RuntimeError: Given groups=1, weight of size [64, 3, 7, 7], expected input[1, 9, 256, 256] to have 3 channels, but got 9 channels instead
> ```

Hello, I encountered the same problem as you before. What are the inputs during the testing phase? I can't seem to get a picture after inpainting.

**Comment by jingyuanli001** [comment]
Thanks for the question. Sorry for the late response.
This problem occurs because the input mask has more than one channel. I was assuming that the mask is a one channel and binary image when I wrote the code. You might solve this by performing channel slice after loading the masks. If any problem still exists, please feel free to contact me. :)

**Comment by jingyuanli001** [comment]
> > Hello, whenver I try to test a pretrained model, I get the following error:
> > ```
> > File "D:\AI\RFR-Inpainting\modules\partialconv2d.py", line 55, in forward
> >     self.update_mask = F.conv2d(mask, self.weight_maskUpdater, bias=None, stride=self.stride, padding=self.padding, dilation=self.dilation, groups=1)
> > RuntimeError: Given groups=1, weight of size [64, 3, 7, 7], expected input[1, 9, 256, 256] to have 3 channels, but got 9 channels instead
> > ```
> 
> Hello, I encountered the same problem as you before. What are the inputs during the testing phase? I can't seem to get a picture after inpainting.

Hi! You might check my post above to see if the problem can be solved. :)

**Comment by GGaoYipeng** [comment]
> > > Hello, whenver I try to test a pretrained model, I get the following error:
> > > ```
> > > File "D:\AI\RFR-Inpainting\modules\partialconv2d.py", line 55, in forward
> > >     self.update_mask = F.conv2d(mask, self.weight_maskUpdater, bias=None, stride=self.stride, padding=self.padding, dilation=self.dilation, groups=1)
> > > RuntimeError: Given groups=1, weight of size [64, 3, 7, 7], expected input[1, 9, 256, 256] to have 3 channels, but got 9 channels instead
> > > ```
> > 
> > 
> > Hello, I encountered the same problem as you before. What are the inputs during the testing phase? I can't seem to get a picture after inpainting.
> 
> Hi! You might check my post above to see if the problem can be solved. :)

Thank you, I have solved this problem. What data do I need to input when testing the pre-trained model. Specifically, what data should be contained in the data_root and mask_root folders. I entered the corrupted image and mask, but it seems that it cannot be repaired. Could I have your WeChat?（vx: G1005004141）

**Comment by jingyuanli001** [comment]
> > > > Hello, whenver I try to test a pretrained model, I get the following error:
> > > > ```
> > > > File "D:\AI\RFR-Inpainting\modules\partialconv2d.py", line 55, in forward
> > > >     self.update_mask = F.conv2d(mask, self.weight_maskUpdater, bias=None, stride=self.stride, padding=self.padding, dilation=self.dilation, groups=1)
> > > > RuntimeError: Given groups=1, weight of size [64, 3, 7, 7], expected input[1, 9, 256, 256] to have 3 channels, but got 9 channels instead
> > > > ```
> > > 
> > > 
> > > Hello, I encountered the same problem as you before. What are the inputs during the testing phase? I can't seem to get a picture after inpainting.
> > 
> > 
> > Hi! You might check my post above to see if the problem can be solved. :)
> 
> Thank you, I have solved this problem. What data do I need to input when testing the pre-trained model. Specifically, what data should be contained in the data_root and mask_root folders. I entered the corrupted image and mask, but it seems that it cannot be repaired. Could I have your WeChat?（vx: G1005004141）

Hi,
The data root should contain the images to be processed. The mask root should contain the corresponding binary masks, with 1 indicating the area to be filled.

**Comment by GGaoYipeng** [comment]
> > > > > Hello, whenver I try to test a pretrained model, I get the following error:
> > > > > ```
> > > > > File "D:\AI\RFR-Inpainting\modules\partialconv2d.py", line 55, in forward
> > > > >     self.update_mask = F.conv2d(mask, self.weight_maskUpdater, bias=None, stride=self.stride, padding=self.padding, dilation=self.dilation, groups=1)
> > > > > RuntimeError: Given groups=1, weight of size [64, 3, 7, 7], expected input[1, 9, 256, 256] to have 3 channels, but got 9 channels instead
> > > > > ```
> > > > 
> > > > 
> > > > Hello, I encountered the same problem as you before. What are the inputs during the testing phase? I can't seem to get a picture after inpainting.
> > > 
> > > 
> > > Hi! You might check my post above to see if the problem can be solved. :)
> > 
> > 
> > Thank you, I have solved this problem. What data do I need to input when testing the pre-trained model. Specifically, what data should be contained in the data_root and mask_root folders. I entered the corrupted image and mask, but it seems that it cannot be repaired. Could I have your WeChat?（vx: G1005004141）
> 
> Hi,
> The data root should contain the images to be processed. The mask root should contain the corresponding binary masks, with 1 indicating the area to be filled.

thank you

**Comment by laolongboy** [comment]
I meeted this problem too. The reason is externel masks used are with 3 channels. 
Can be solved by comment this line(model.py，line 90): 
# masks = torch.cat([masks]*3, dim = 1)
