### ISSUE TITLE
torch.load("pretrain_model") ERROR

### ISSUE THREAD

**Issue by yunhao1996** [jingyuanli001/RFR-Inpainting#15]
Hello! I'm interested in your paper. Thanks for your pre_trained model.
When loading the pre_trained model for testing results,  I found that the model couldn't load.  My verification code is as follows：
`import torch
`
`
a = torch.load('/home/sq/Codes/RFR-Inpainting-master/pre_model/checkpoint_celeba.pth')
`

The results of terminal operation as follows:

Traceback (most recent call last):
  File "111.py", line 3, in <module>
    a = torch.load('/home/sq/Codes/RFR-Inpainting-master/pre_model/checkpoint_celeba.pth')
  File "/home/sq/anaconda3/envs/outpainting/lib/python3.6/site-packages/torch/serialization.py", line 387, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/home/sq/anaconda3/envs/outpainting/lib/python3.6/site-packages/torch/serialization.py", line 576, in _load
    deserialized_storage_keys = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: pickle data was truncated

Environment：
`
python=3.6
pytorch=1.1.0
`

Do you have this problem? Or there are some errors about this pre_trained model. 
Thanks.

**Comment by jingyuanli001** [comment]
Hi,

Thank you for your question.
I've checked the pertained model and it turns out that the model file is damaged when I was uploading it to google cloud.
I will upload that model again later this week.

Thank you!

**Comment by yunhao1996** [comment]
Thanks to your reply! Please allow me to disturb you again.

I notice that the pre_trained model of Places2 datasets hasn't been released yet. Can you upload it as soon as possible？
I love Wuhan University！

Best wishes to you!

**Comment by avitalsh** [comment]
Hi @jingyuanli001,

I've downloaded the pretrained model file today and get the same error. 
Is this the new version of the model or is it still the corrupted one?

Thanks.

**Comment by jingyuanli001** [comment]
> Hi @jingyuanli001,
> 
> I've downloaded the pretrained model file today and get the same error.
> Is this the new version of the model or is it still the corrupted one?
> 
> Thanks.

The one you downloaded should be the corrupted one. I've uploaded a new one and you might check it.

Thank you
