### ISSUE TITLE
Question about the pretrain model

### ISSUE THREAD

**Issue by ChujunWhu** [jingyuanli001/RFR-Inpainting#16]
Hi jingyuan, I would like to know the mask ratio of the pretrain model for CelebA. Have you used 40%-50%  to train the model? And are the results under different mask ratio reported in your paper tested using a single pretrain model, or  have  you trained several models for different mask ratios. Thx!

**Comment by jingyuanli001** [comment]
> Hi jingyuan, I would like to know the mask ratio of the pretrain model for CelebA. Have you used 40%-50% to train the model? And are the results under different mask ratio reported in your paper tested using a single pretrain model, or have you trained several models for different mask ratios. Thx!

The results are from a single model trained with various mask ratios. The maximum mask ratio is ~60%.

**Comment by jingyuanli001** [comment]
> Hi jingyuan, I would like to know the mask ratio of the pretrain model for CelebA. Have you used 40%-50% to train the model? And are the results under different mask ratio reported in your paper tested using a single pretrain model, or have you trained several models for different mask ratios. Thx!

You might check the mask generation process described in partial convolution's paper. We followed the configurations in that paper.
