### ISSUE TITLE
Larger picture testing

### ISSUE THREAD

**Issue by huoxiangzuo** [jingyuanli001/RFR-Inpainting#17]
Hi, I am very interested in your work. Tested the 256x256 image restoration effect is very good. How do I enter a larger picture for testing?

**Comment by jingyuanli001** [comment]
To test a larger image, you might change the 'target_size' augment in the run.py file. However, one of the current limitation of the code is that it only support squared input. You might need some further modifications to dataset.py to allow rectangular inputs.

**Comment by huoxiangzuo** [comment]
Okay, I will make changes, thank you for your reply.
