### ISSUE TITLE
Verification Set

### ISSUE THREAD

**Issue by huoxiangzuo** [jingyuanli001/RFR-Inpainting#20]
Hey, thank you very much for sharing. I have a question, the verification set is not distinguished in the code, will it affect the final result?

**Comment by jingyuanli001** [comment]
> Hey, thank you very much for sharing. I have a question, the verification set is not distinguished in the code, will it affect the final result?

Hi, thanks for you interest!
It shouldn't affect the final results much, because the learning rate adjustment is done by manual control. However, adding a learning rate scheduler might further improve the performance of the network.

**Comment by huoxiangzuo** [comment]
Thanks.
