### ISSUE TITLE
Should this line of code be “bz, nc, h, w = foreground.size()”

### ISSUE THREAD

**Issue by TianyuMeng** [jingyuanli001/RFR-Inpainting#22]
First of all, thanks for your wonderful work!
I think the picture should keep its original size during the test process. But in the process, I found a bug in the 17th line of “modules/Attention.py”. I suppose it should be "bz, nc, h, w = foreground.size()"

**Comment by jingyuanli001** [comment]
> First of all, thanks for your wonderful work!
> I think the picture should keep its original size during the test process. But in the process, I found a bug in the 17th line of “modules/Attention.py”. I suppose it should be "bz, nc, h, w = foreground.size()"

Good catch! Indeed, it should be bz, nc, h, w, instead of the current one.
