### ISSUE TITLE
About the division of dataset Celeba

### ISSUE THREAD

**Issue by laolongboy** [jingyuanli001/RFR-Inpainting#27]
Hi, I get some awesome results on Celeba dataset using your released model. But I dont know if I sample the images from training set. So can you release your testing set list in Celeba?

**Comment by jingyuanli001** [comment]
> Hi, I get some awesome results on Celeba dataset using your released model. But I dont know if I sample the images from training set. So can you release your testing set list in Celeba?

I thought the celeca dataset provides training, testing and validation splits itself. The corresponding file list (a txt file) should be on the same folder as the training images, is it convenient for you to check that file? We use the official training set to train our model.

**Comment by laolongboy** [comment]
Thanks a lot. I found that.
