### ISSUE TITLE
Training on Celeba-HQ datasets 

### ISSUE THREAD

**Issue by laolongboy** [jingyuanli001/RFR-Inpainting#28]
![image](https://user-images.githubusercontent.com/25175047/100298320-cd0d4e80-2fcb-11eb-8964-a7289cc8d8fc.png)
![image](https://user-images.githubusercontent.com/25175047/100298326-d0a0d580-2fcb-11eb-95b1-d485621b4b35.png)
I am not sure the results are reliable. Will u release Celeba-hq models?

**Comment by jingyuanli001** [comment]
Hi. Unfortunately, we are not planning to release the model for Celeb-HQ. However, when we were developing the model, we've indeed trained our model on CelebA-HQ dataset and the results are also satisfactory. For your case, I would suggests you to train the model for a longer time, and be sure to do adequate finetuning before testing (which is significant for stabilize the performance). You might also insert one or two extra partial convolution layers to down-sample the images in the inpainting procedure.
