### ISSUE TITLE
Error loading celeba model

### ISSUE THREAD

**Issue by haolin512900** [jingyuanli001/RFR-Inpainting#29]
HI,Thank you for sharing this great project
But there was an error loading the model，The error is as follows：
‘’_ pickle.UnpicklingError : pickle data was truncated‘’
It may be your model upload error。
I hope you can give us an answer，Thank you

**Comment by jingyuanli001** [comment]
> HI,Thank you for sharing this great project
> But there was an error loading the model，The error is as follows：
> ‘’_ pickle.UnpicklingError : pickle data was truncated‘’
> It may be your model upload error。
> I hope you can give us an answer，Thank you

Hi, thank you for your question. I would like to know when did you download the model? I have uploaded a new model before to replace the truncated one, and it should work correctly now.

**Comment by haolin512900** [comment]
Thank your answer，the question have been sovled！

**Comment by haolin512900** [comment]
> > HI,Thank you for sharing this great project
> > But there was an error loading the model，The error is as follows：
> > ‘’_ pickle.UnpicklingError : pickle data was truncated‘’
> > It may be your model upload error。
> > I hope you can give us an answer，Thank you
> 
> Hi, thank you for your question. I would like to know when did you download the model? I have uploaded a new model before to replace the truncated one, and it should work correctly now.

Thank your answer，the question have been sovled！
