### ISSUE TITLE
About trainging masks dataset

### ISSUE THREAD

**Issue by haolin512900** [jingyuanli001/RFR-Inpainting#30]
Hi，Thank you for your great project again！
    How do you divide the masks training dataset from pconv? Whether to use all masks training data sets as training data sets ?

**Comment by haolin512900** [comment]
> Hi，Thank you for your great project again！
> How do you divide the masks training dataset from pconv? Whether to use all masks training data sets as training data sets ?

or you training your dataset use the'mask_mode==1'(the mask data from the your code generate)

**Comment by haolin512900** [comment]
Or you train your model using mask_mode==1？

**Comment by jingyuanli001** [comment]
For the training mask in pconv's paper, you might first randomly dilate the holes to enlarge the masked region (this could be done with max pooling on binary mask). Then you should do random cropping, flipping and resizing to augment the masks. For the mask preparation details, you might refer to the procedure released by Edge-Connect. You can also use mask_mode 1 to train the model to inpaint with random masks.

**Comment by haolin512900** [comment]
Thank your reply! good lucky

**Comment by haolin512900** [comment]
Thank your reply! Good lucky




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jingyuanli001/RFR-Inpainting"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月24日(星期四) 晚上8:42
收件人:&nbsp;"jingyuanli001/RFR-Inpainting"<RFR-Inpainting@noreply.github.com&gt;;
抄送:&nbsp;"1250404756"<1250404756@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [jingyuanli001/RFR-Inpainting] About trainging masks dataset (#30)





 
For the training mask in pconv's paper, you might first randomly dilate the holes to enlarge the masked region (this could be done with max pooling on binary mask). Then you should do random cropping, flipping and resizing to augment the masks. For the mask preparation details, you might refer to the procedure released by Edge-Connect. You can also use mask_mode 1 to train the model to inpaint with random masks.
