### ISSUE TITLE
Some questions regarding source code

### ISSUE THREAD

**Issue by xiankgx** [jingyuanli001/RFR-Inpainting#31]
[link](https://github.com/jingyuanli001/RFR-Inpainting/blob/master/modules/Attention.py#L10-L11)

Two attributes 'stride' and 'prop_kernels' doesn't seem to be used. Can I remove them?

[link 2](https://github.com/jingyuanli001/RFR-Inpainting/blob/master/modules/RFRNet.py#L150-L151)

Line 150 seems to be redundant with the existence of line 151, please correct me if I'm wrong.

**Comment by jingyuanli001** [comment]
Hi, thanks for printing this out. Yes, some of the parameters in the attention module is currently redundant, and you can safely remove them. This is the same for the second issue you pointed out.

**Comment by xiankgx** [comment]
Thank you author, I'm training a places2 model, hope it will work out well so I can wrap up my work.
