### ISSUE TITLE
How to replace 8 residual blocks of EageConnnect with RFR Moudle

### ISSUE THREAD

**Issue by WGwg** [jingyuanli001/RFR-Inpainting#36]
EageConnect is ordinary convolution, not partial convolution，Please tell me how to replace it, thank you very much

**Comment by ZHANG-hengzhi** [comment]
大佬，你这边代码改成功了吗

**Comment by WGwg** [comment]
> 大佬，你这边代码改成功了吗

没有，我已经放弃了
