### ISSUE TITLE
model test issue

### ISSUE THREAD

**Issue by pbelfort** [jingyuanli001/RFR-Inpainting#40]
Hi... I had tried to run your code, but i had this kind of issue!
When I run the code, I have no problem and it's created the checkpoint path with this argument (python run.py), but when I put the argument to test (python run.py --test), I have no problem too, but its not created the result path with the regenerated images.
Do you now whats wrong with my attempt?

![issue](https://user-images.githubusercontent.com/42588868/109952836-1271a400-7cbe-11eb-9991-1ac8d6e77009.png)

**Comment by xiankgx** [comment]
For the second problem, your masks is 9 channels instead of the required 3. If your masks is stored in 3 channels, then modify code to not stack the mask to produce 9 channel mask.

The last problem, the code fails to find your training files. Check the code to see if your files location is as expected.

**Comment by pbelfort** [comment]
Thx for reply... But where in the code i have to change this?

**Comment by xiankgx** [comment]
For the 9 vs 3 channel mask problem, just disable this line, or make your mask single channel by taking just the first channel.

https://github.com/jingyuanli001/RFR-Inpainting/blob/master/model.py#L87

**Comment by m-chaves** [comment]
Hi, I'm using a 3 channel png image and mask, but I get the following error  "expected input[1, 4, 256, 256] to have 3 channels, but got 4 channels instead".  

First, I got this other error: "expected input[1, 12, 256, 256] to have 3 channels, but got 12 channels instead", so I disabled the line you suggested (https://github.com/jingyuanli001/RFR-Inpainting/blob/master/model.py#L87). Nevertheless, it looks like it's adding an extra channel at some point. I'm using the Paris Street View pre-trained model.

**Comment by xiankgx** [comment]
Your masks is 4 channels. Make it one channel.

**Comment by m-chaves** [comment]
Could you provide me an example of the type of mask that should be used? 
The mask I'm using is available in: https://github.com/JiahuiYu/generative_inpainting/blob/master/examples/places2/case1_mask.png. The corresponding image is: https://github.com/JiahuiYu/generative_inpainting/blob/master/examples/places2/case1_raw.png. 

I tried making the mask of 1 channel, but then I get other problems later, such as "RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 1".

**Comment by 01SHENyankun** [comment]
你好，我遇到了和你一样的问题，能帮忙指导一下嘛
