### ISSUE TITLE
Final checkpoint not being saved if it already exists

### ISSUE THREAD

**Issue by Cristy94** [jingyuanli001/RFR-Inpainting#46]
The problem is here:

https://github.com/jingyuanli001/RFR-Inpainting/blob/faed6f154e01fc3accce5dff82a5b28e6f426fbe/model.py#L76-L78

The final line (`save_ckpt`) should not be inside the if.

**Comment by jingyuanli001** [comment]
I see, thanks for pointing this out! I thought I was having some assumptions regarding the path...
