### ISSUE TITLE
Bad testing result

### ISSUE THREAD

**Issue by liyujiejiejie** [jingyuanli001/RFR-Inpainting#48]
i have trained RFRNet on my own dataset, i got great trainng result ,but the test result is terrible, the difference between trainset and testset is different mask , could u help me?

![image](https://user-images.githubusercontent.com/30972697/112415644-1fcefb00-8d5f-11eb-9490-4734418093ec.png)

**Comment by jingyuanli001** [comment]
Have you fine-tuned the model?  The testing results might be distorted due to insufficient fine-tuning. Besides, the format of the testing mask might also be important, please ensure that the mask has only 0 and 1 in it.
