### ISSUE TITLE
Grayscale images?

### ISSUE THREAD

**Issue by turian** [jingyuanli001/RFR-Inpainting#52]
It appears the code only support RGB images. Can you add support for grayscale too?

**Comment by kopop8** [comment]
I added `  img = imread(self.data[index], as_gray=False, pilmode="RGB")` when readin images in load_item function in dataset.py

**Comment by turian** [comment]
@kopop8 that will create a 3-channel model, which will have 3x the number of parameters?

**Comment by kopop8** [comment]
Thats true., this was just a quick workaround i used.

**Comment by turian** [comment]
@kopop8 yes thanks, I've done something like that too
