### ISSUE TITLE
training data and mask

### ISSUE THREAD

**Issue by micktsai** [jingyuanli001/RFR-Inpainting#9]
Hello, I have some problem about training your model.
What should I put in the folder of data_root and mask_root?

**Comment by jingyuanli001** [comment]
Hi,

They should be the directories that containing '.jpg' or '.png' image files.
To fit into your own files, you may modify the 'load_list' method in 'dataset.py' file. :)

**Comment by micktsai** [comment]
Sorry, I didn't ask clearly.
I have no idea about how many image should I put in data_root, One is enough or more is better?
And the image in mask_root should I mask it by myself?

**Comment by jingyuanli001** [comment]
For training, more data should be better. For testing, you can simply put the testing images in the folder. As for the mask, you might directly set mask mode to 1 to generate random mask. Or instead, you can use an external mask dataset, like what was given by Partial Convolution's Project.
